### ISSUE TITLE
why is parent -> child communication bad

### ISSUE THREAD

**Issue by vhpoet** [dollarshaveclub/postmate#10]
> The parent cannot send messages. However, a simple request to a function in the child via child.get is possible, and can solve most scenarios, but is advised against.

Why?

**Comment by Sind** [comment]
+1

Since the child model can have functions, I would like to be able to send parameters when calling a function in the child.

**Comment by jakiestfu** [comment]
The purpose is to keep logic for each respective environment in their environments.

@Sind A couple versions ago, using the `get` function accepted additional arguments, but that was deprecated before long. Reason being is that when you `get` a property, it's value shouldn't change based off of arbitrary arguments.

If you want to provide additional data to the child when you make a get request, consider setting a default model when instantiating the parent.

@vhpoet Can you provide a use case which Postmate cannot solve without parent -> child communication?

**Comment by Sind** [comment]
@jakiestfu While I can understand wanting to keep  the logic separate, the purpose of this API is to allow for communication with a child iframe. I feel like this isn't currently achieved nicely, if the parent only can send messages at handshake.

If the problem is a naming convention, `get`, may I suggest adding an additional function? maybe `call`?

And for what it's worth, my current problem most likely *can* be solved through the `default model`. However, it is not documented anywhere in the readme how the child can access these values.

**Comment by jakiestfu** [comment]
@Sind I'm open to the discussion, and hope I don't sway you from sharing.

Do you think arbitrary arguments should be allowed to be sent to a get request?

Also, that information is not documented because it is a standard of computer science.

```javascript
var model = {
  foo: 'bar'
};
new Postmate.Model(model);

// Child can access anything from model at a later point
```

**Comment by Sind** [comment]
@jakiestfu I do think that sending information from parent to child in some way or another should be possible, and I think doing it through function arguments is an elegant solution. This way, the child has easy control over how the data is handled.
Maybe there's an argument to be made for limiting the parameters to non-executable types or such, to make it safer for the child page, but I think that arbitrary data is fine.

It could be part of the `get` call, or maybe something new. Maybe there can be a separate `call` function that allows passing arguments, or a `set` function that simply sets the variable, and the child can listen on that. (Personally, I'd go for the `call` solution, but I wouldn't object to the other ones) 

For reference, here's what I want to use PostMate for: I am serving a site that other people can embed into their pages, and I would like a to have a method for these people to easily customize the site I'm serving. Customization such as changing the colors to better fit with their own page, or changing the text to something they think fits better(or maybe a translation), etc.

In general, the default model solution should be good enough for this, but I can imagine some cases where being able to message the child whenever can be useful. For example, imagine a case where someone who is embedding my page has a feature on their page to change the site theme. It would be nice for them to them to then have a way to also change the colors in the embedded page, without having to reload it or something.

And thanks for the code snippet; I'll be trying it out later today.

**Comment by jakiestfu** [comment]
I see. That's an interesting use case. Let me mull this over and discuss this with some colleagues and we can come to a resolution soon! :)

**Comment by vhpoet** [comment]
@jakiestfu I have a very similar use case.

**Comment by Sind** [comment]
@jakiestfu any updates on this issue?

**Comment by jakiestfu** [comment]
@sind I'm adding support for a call method that takes parameters but will not retrieve values. Currently writing tests for it and I will cut a new version by EOD

**Comment by jakiestfu** [comment]
@Sind @vhpoet 

Update to version `1.1.0`, let me know how this works for you guys!

https://github.com/dollarshaveclub/postmate/commit/b1a60cb841fd0e80b2977985cca9cc68a7edb653

**Comment by vhpoet** [comment]
@jakiestfu also https://github.com/dollarshaveclub/postmate#i-want-to-send-messages-to-the-child-from-the-parent

**Comment by jakiestfu** [comment]
Thanks, @vhpoet!

**Comment by Aaronius** [comment]
It seems to me that it would be simpler if `get`, `call`, and `emit` were boiled down to a single API. Examples:

```
// call a method
child.call('doTheHarlemShake');
parent.on('doTheHarlemShake', function() { shake(); });

// pass an argument
child.call('setRandomId', randomId);
parent.on('setRandomId', function(value) { console.log(value);  });

// pass an argument and receive return value
child.call('validate', onlyIncludeTextfields).then(function(isValid) { console.log(isValid); });
parent.on('validate', function(onlyIncludeTextfields) { return true;  });

// get a value
child.call('getRandomId').then(function(randomId) { console.log(randomId); });
parent.on('getRandomId', function() { return 123; });

// notify that an event has occurred
child.call('onDoorOpened', 3);
parent.on('onDoorOpened', function(doorNumber) { if (doorNumber === 3) { declareWinner(); });
```

Regardless of whether you're "calling", "getting", or "emitting", you're always really just calling a method on the other side, right?
