### ISSUE TITLE
Possible Bug In sendHandshakeReply() 

### ISSUE THREAD

**Issue by lots0logs** [dollarshaveclub/postmate#100]
This condition will always be true even when there are no ports in the array:

https://github.com/dollarshaveclub/postmate/blob/e57a719c5128fd2632a459eac6aa7f826c94e015/src/postmate.js#L440-L445

I stumbled upon this because the latest release doesn't work when an iframe is the parent window of a child iframe. The code on master appears to work in my testing thus far (apart from the above issue).

**Comment by Andarist** [comment]
Could u describe ur issue in more detail? When exactly the ports array would be empty?
