### ISSUE TITLE
Supported browsers/versions ?

### ISSUE THREAD

**Issue by tttp** [dollarshaveclub/postmate#108]
Hi,

I didn't find on your documentation what are the browsers (and minimum version) supported. Is this described somehwere?

**Comment by yowainwright** [comment]
@tttp what about [this](
https://github.com/dollarshaveclub/postmate/blob/master/.babelrc)?

Does that help?

Would you like to submit a PR with a readme update?

**Comment by tttp** [comment]
Hi,

I decided to go with another lib https://github.com/davidjbradshaw/iframe-resizer (>ie8), that has an API that isn't as nice as postmate, but was good enough for what I needed ;)
