### ISSUE TITLE
Child Frame Navigation in version 1.4.7

### ISSUE THREAD

**Issue by benpolinsky** [dollarshaveclub/postmate#120]
In the case where a child frame navigates to a new page (user clicks a link in the frame), it seems like a connection between a parent and _the new_ child is not maintained.

I've enabled logging, and the parent logs "Parent: Received handshake reply from Child" after the navigation, but no events are being sent. 

However, in version 1.4.1, the connection seems to be maintained, and messages are sent.

Any ideas? I can try to reproduce this minimally, if that would help.

Thanks.

**Comment by yowainwright** [comment]
@benpolinsky, for debugging purposes, could you try version `1.4.2`? 🙏

In that version origin resolution logic was updated.

**Comment by benpolinsky** [comment]
Okay cool. Here is an example on 1.4.2 with debugging enabled.

https://laughing-hermann-c9472b.netlify.com/

It does look like the events are being sent from the child and received by the parent. A couple things to note:

1. After navigation, parent calls are not being made again from within the handshake callback scope. However (this isn't in the above example, I've just testing it locally) if I listen for an event from the child and then take make calls, the calls do take place on navigation. Perhaps this is expected behavior.

2. After one link is clicked, you can see in the console that a handshake attempt is unsuccessful - and this runs 5 times as expected due to the maxHandshakeRequests === 5. However, if you click another link, the handshake requests seem to continue infinitely. 

I suppose the maxHandshakeRequests issue (if it is indeed an issue) could be solved by comparing `attempt >= maxHandshakeRequests` as opposed to `attempt === maxHandshakeRequests`

**Comment by yowainwright** [comment]
@benpolinsky this is awesome feedback! Thank you. I will make updates based on the feedback in your [comment](https://github.com/dollarshaveclub/postmate/issues/120#issuecomment-429353439) and the feedback [here](https://github.com/dollarshaveclub/postmate/issues/114).

**Comment by yowainwright** [comment]
@benpolinsky thank you so much for your debugging help. Please let me know if version `1.4.8` is stable for you.

**Comment by benpolinsky** [comment]
@yowainwright of course - glad to help! I've done some initial testing and `1.4.8` works great.

Appreciate the quick turnaround on this!

**Comment by yowainwright** [comment]
@benpolinsky thank you!
