### ISSUE TITLE
Child fails to complete handshake

### ISSUE THREAD

**Issue by admench** [dollarshaveclub/postmate#136]
## What Is the issue?
Getting this in the console, following your basic example:
```
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': Invalid target origin 'null' in a call to 'postMessage'.
```

## Provide issue context below using code examples, images, or links

![screen shot 2018-11-19 at 09 15 53](https://user-images.githubusercontent.com/672916/48697156-d1801f00-ebdb-11e8-9b05-1f2181dd6c46.png)

----
Parent instantiation:
```
import Postmate from "postmate"
Postmate.debug = true

const handshake = new Postmate({
    container: document.getElementById('virtual-adviser-initial-container'),
    url: 'https://virtual-adviser.test/cross-origin-enquiry/', 
    classListArray: ["mw-full"]
});


handshake.then(child => {
    child.get('height')
      .then(height => child.frame.style.height = `${height}px`);
    child.on('some-event', data => console.log(data)); // Logs "Hello, World!"
});
```

Tried using `v1.4.2` and `^v1.4.8` with the same issue. Can you shed any light as to why this would be happening? Many thanks 👍🏼

**Comment by dLaMothe** [comment]
+1
