### ISSUE TITLE
Latest bugfixes not released yet (still on 1.5.0)

### ISSUE THREAD

**Issue by mrcoles** [dollarshaveclub/postmate#176]
## What Is the issue?

I’m seeing some console errors related to the postmate sanitize function:

```
Uncaught TypeError: Cannot use 'in' operator to search for 'postmate' in …
```

## Provide issue context below using code examples, images, or links

I’m seeing that this bug was fixed with this update: https://github.com/dollarshaveclub/postmate/commit/8470cb3beec8637452d9f8ceedaa3fd55a839c6a#diff-3345c6e09a722d091244b0d537a55619

I understand this is more noise than a real issue, since it’s just an error in message-passing that isn’t meant for the postmate model, but noisy errors lead to actual errors getting ignored. 

Can you release an update with that change, either 1.5.1 or 1.6.0?

**Comment by ot-raypeters** [comment]
Following up on this thread... this bug is causing postmate to be a noisy neighbor.

My team and I would really like to have this resolved

**Comment by yowainwright** [comment]
@mrcoles @ot-raypeters thanks for the reminder. I will give Postmate some love ASAP. 😄

**Comment by jakiestfu** [comment]
Thanks for your patience, friends. `v1.5.1` is now released. Let me know if this alleviates things.

https://www.npmjs.com/package/postmate
