### ISSUE TITLE
Is it working with window.open ?

### ISSUE THREAD

**Issue by LeaklessGfy** [dollarshaveclub/postmate#21]
Hi !

Your lib seems to be really cool but I want to know if it work with a window.open created window or if it just work with iframes ?

Thanks :)

**Comment by jakiestfu** [comment]
I think it's designed to work with only iFrames, but with a little bit of work, it can easily support opening windows as well. Would you care to take a stab at it and send a PR?

**Comment by LeaklessGfy** [comment]
Yes with pleasure

**Comment by yowainwright** [comment]
@LeaklessGfy thanks! This ticket is being closed b/c of inactivity. Perhaps it will be covered [here](https://github.com/dollarshaveclub/postmate/issues/49).
