### ISSUE TITLE
Is there an online demo

### ISSUE THREAD

**Issue by dmitrymar** [dollarshaveclub/postmate#28]
I'm trying to choose between this library, [xcomponent](https://github.com/krakenjs/xcomponent), and [easyXDM](https://github.com/oyvindkinsey/easyXDM) and I was wondering if you guys have a working online demo?

**Comment by yowainwright** [comment]
@dmitrymar sorry for the late response it is in the works. This issue can be tracked [here](https://github.com/dollarshaveclub/postmate/issues/37). ~Thanks! 🙏
