### ISSUE TITLE
Ember example

### ISSUE THREAD

**Issue by jgwhite** [dollarshaveclub/postmate#3]
Hi there. This library looks awesome. Could you give an example of how one would import it into an Ember app?

**Comment by jakiestfu** [comment]
There is no ember plugin for Postmate (yet), but it is a possibility in the future. To include it in your Ember app, do the following:

`bower install postmate --save`

If you're including it in a separate addon, you'll create a blueprint and add the following to it:

```javascript
module.exports = {
  normalizeEntityName: function() {},

  afterInstall: function() {
    return this.addBowerPackageToProject('postmate');
  }
};
```


If you want to just add it via your `ember-cli-build.js` file and use it as a global

```javascript
app.import('bower_components/postmate/build/postmate.min.js');
```

**Comment by jgwhite** [comment]
Perfect, thanks!
