### ISSUE TITLE
Uncaught (in promise) Handshake Reply Failed

### ISSUE THREAD

**Issue by SoapGentleMan** [dollarshaveclub/postmate#31]
thougth there is the same issue, but my question is not same to it.
i can normally use it, but when my project initial, it will cause   "Uncaught (in promise) Handshake Reply Failed", then it runs normally

**Comment by yowainwright** [comment]
I think this issue may have been [fixed](https://github.com/dollarshaveclub/postmate/pull/35). 🙏
