### ISSUE TITLE
ie11 childOrigin get wrong url cause postmessage fail

### ISSUE THREAD

**Issue by lerit** [dollarshaveclub/postmate#32]
i debug the source code,the function resolveOrigin try to get target origin by the line:
a.origin || a.protocol + '//' + a.hostname
but in my ie 11,origin is undefined,and protocol and hostname is empty string
![00](https://user-images.githubusercontent.com/4743467/30679293-207d984e-9ecb-11e7-9771-2558c9abf156.png)

**Comment by yowainwright** [comment]
I hope this issue is fixed. Reach out if not.
