### ISSUE TITLE
IE10 - method 'on' not invoked before Parent: Received event emission

### ISSUE THREAD

**Issue by BerlinChan** [dollarshaveclub/postmate#44]
Before test in IE, merge #43 
When parent <-> child handshake is complete, and child emit a event immediately, like:
`
        handshake.then(parent => {
            parent.emit('some-event', 'Hello, World!');
        });
`

in IE10, the if condition is `false`, so the event is not fired.
`
if (name in this.events) {
          this.events[name].call(this, data)
        }
`

Delay child's emit can fix this temporary
`
handshake.then(parent => {
            setTimeout(() => parent.emit('some-event', 'Hello, World!'), 2000);
        });
`

But how to fix this really?

**Comment by yowainwright** [comment]
@BerlinChan Thanks for your response and sorry for the delay. 

We recently did some minor patch work. I'm curious what you're seeing now ...?
