### ISSUE TITLE
[discussion] MessageChannels

### ISSUE THREAD

**Issue by Andarist** [dollarshaveclub/postmate#56]
Have you considered using MessageChannels instead of bare postMessage? It potentially could allow for more secure communication between parent & the child

**Comment by Andarist** [comment]
It's supported even by IE10, dunno what's your standards about browser support.

The only iffy part of this API is that establishing the connection is somewhat not secure or at least I don't know how to make it secure because you need to establish it with regular `postMessage` but after you establish it (handshake :P) you have 1to1 secure line, no other script is be able to spy on passed messages (which is not true for regular postMessage which is a broadcast rather than a targeted emit)

**Comment by jakiestfu** [comment]
Interesting thought, @Andarist. Care to explain in further detail how you think this could benefit the library, and what it is we're looking for when we define "secure"? Maybe some pseudocode examples would help me understand better :)

**Comment by Andarist** [comment]
By secure I mean that during the "connection" no external script is able to listen to interchanged messages. With regular `postMessage` any script on the site can simply `addEventListener` and spy on the communication.

I don't think there is much pseudocode I could provide to explain this better, it's just an alternative way of exchanging messages with familiar `postMessage` interface, only through MessagePorts and not through windows. You can check out how it works [here](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel#Example)

**Comment by Andarist** [comment]
Any thoughts about this one?

**Comment by yowainwright** [comment]
@Andarist I want this feature! ...As long as it can be added as a feature version not breaking

**Comment by Andarist** [comment]
sure thing, regular postMessage might still be used as a fallback

gonna work on this when I find time to do so

**Comment by yowainwright** [comment]
Sounds awesome @Andarist!

**Comment by agurtovoy** [comment]
@Andarist FWIW, checkout https://github.com/ganimomer/message-channel-promise
