### ISSUE TITLE
How does postmate ensure that messages are only coming from authorized origins?

### ISSUE THREAD

**Issue by austinrivas** [dollarshaveclub/postmate#6]
Hey @jakiestfu 

Great work as usual :)

I was curious about how postmate ensures that all messages are coming from authorized origins to avoid xss attacks.

I saw [sanitize](https://github.com/dollarshaveclub/postmate/blob/master/src/postmate.js#L139), which appears to be checking `parentOrigin` in the `ChildAPI` constructor, but I was unable to see where each `parentOrigin` is validated on a per message basis.

Give the guys my best, and keep up the good work.

EDIT: NVM I just realized that it was declaring an event handler in the `ChildAPI` constructor.

**Comment by jakiestfu** [comment]
Thanks for opening this issue @austinrivas! Glad you found a resolution to it, too! 🍻
