### ISSUE TITLE
Change the frame URL

### ISSUE THREAD

**Issue by juanpmarin** [dollarshaveclub/postmate#70]
Hi
Is it possible to change the frame url ? and if it is, how is the handling of the onload

**Comment by juanpmarin** [comment]
@yowainwright How is going ? 
I want to dynamically change the frame URL beign able to don't loose the communication

**Comment by yowainwright** [comment]
@juanpmarin hey! Thanks for your response. Your insights are appreciated. 

Here's my initial response:

Dynamically changing the child (`<iframe>`'s `src`) is not supported by Postmate. Postmate uses [postmessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) and soon [messageChannels](). Both APIs expect a secure handshake between a parent (a webpage) and a child (an `<iframe>`). 

What are your thoughts? Would query params work? Have you tried?

**Comment by juanpmarin** [comment]
Query params would not work because we have different apps on different hosts and we want to change dynamically between pages

**Comment by yowainwright** [comment]
@juanpmarin thanks for that insight. 

A good use-case of Postmate is securely sharing information between a webpage and an iframe—like a form with personal information. 

To me, this means that allowing information to be shared between a parent webpage and an iframe. Different/changing sources is a not a best practice for that. That issue can be bypassed and security can be maintained is by setting up a secure host for iframe src's and then whitelisting that host to allow for cross origin sharing. ...That's my abstract consideration.

**Comment by juanpmarin** [comment]
@yowainwright sorry, I don't got what you suggestion means, you say that we should have an unique host that routes to the others apps ?

**Comment by yowainwright** [comment]
Sorry, I was going into our own use case. 

To accomplish that your initial goal (as I understand it),  the ur could be changed with JS or a new Postmate instance can be created.
