### ISSUE TITLE
it will be blocked when page is across origin.

### ISSUE THREAD

**Issue by BryanYang** [dollarshaveclub/postmate#91]
the code at line 218 is not work when the source is across origin:
```
    // when parent page is across origin, the browser will block this.
    this.source.addEventListener('message', (e) => {
      if (!sanitize(e, this.parentOrigin)) return

      if (process.env.NODE_ENV !== 'production') {
        log('Child: Received request', e.data)
      }
```
**so, whether we should judge the parent's origin before bind the enent listener ?**

**Comment by yowainwright** [comment]
@BryanYang there's this issue and your [PR](https://github.com/dollarshaveclub/postmate/pull/92). 

Are you still interested in helping with Postmate?

Sorry it took me a bit to get back to you.
